drop sequence SQ_ANIMAIS;
drop sequence SQ_PESSOAS;
drop sequence SQ_SERVICOS;

drop table TB_ANIMAL CASCADE CONSTRAINTS;
drop table TB_PF CASCADE CONSTRAINTS;
drop table TB_PJ CASCADE CONSTRAINTS;
drop table TB_SERVICO CASCADE CONSTRAINTS;